#!/bin/bash
#
## Utility function
#


#  call the implementation of the automation use cases
#  IN : N/A
#  OUT: N/A
function test_case_function_run()
{
    if [ x"${TEST_CASE_FUNCTION_SWITCH}" == x"on" ]
    then
        ${TEST_CASE_FUNCTION_NAME}

	if [ x"${MESSAGE}" == x"PASS" ];then
		lava_report "${TEST_CASE_TITLE}" pass "${Developer}" "${MESSAGE}"
        test_report "${TEST_CASE_TITLE}" pass "${MESSAGE}" "${Developer}" "${Tester}" "${DateTime}"
	else
		lava_report "${TEST_CASE_TITLE}" fail "${Developer}" "${MESSAGE}"
        test_report "${TEST_CASE_TITLE}" fail "${MESSAGE}" "${Developer}" "${Tester}" "${DateTime}"
	fi
    else
        MESSAGE="BLOCK\tno automated use cases were implemented."
    fi
}

# Output log file header
# IN : N/A
# OUT: N/A
function writeLogHeader
{
    echo -e "JIRA ID\tDesigned Requirement ID\tTest Case ID\tTest Item\tTest Case Title\tAutomated scripts\tRealize the function\tSwitch\tResult\tReason" > ${OUTPUT_TEST_DB_FILE}
    return 0
}

# Install the perf tool
# IN : N/A
# OUT: N/A
function InstallPerf(){
    tmp_path="${PERF_TOP_DIR}/../common_tool"
    cp ${tmp_path}/perf /usr/bin
}
