#!/bin/bash
#
#


#Automated data files exported in test cases.
TEST_CASE_DB_FILE="data/pcie_test_case.table"
#
OUTPUT_TEST_DB_FILE="data/report.csv"
#
TEST_CASE_FUNCTION_SWITCH=""
#
TEST_CASE_FUNCTION_NAME=""
#
MESSAGE=""

#  Common tools directory path
COMMON_TOOL_PATH="common_tool"

#  Test case code directory path
TEST_CASE_PATH="pcie_autotest/case_script"

#  Save all disk partition names
declare -a ALL_DISK_PART_NAME

#  fio tools configuration file
FIO_CONFG="fio.conf"

# FIO tools IO Read and write mode
# FIO_RW=("read" "write" "randrw" "randread" "randwrite" "rw" "readwrite" "randrw")
FIO_RW=("read" "write")

# FIO tool parameter list
FIO_PARAMETER_LIST="
[global]
rw=read
direct=1
ramp_time=1
ioengine=psync
iodepth=128
numjobs=1
bs=4k-4M
;zero_buffers=1
group_reporting=1
;ioscheduler=noop
;gtod_reduce=1
;iodepth_batch=2
;iodepth_batch_complete=2
runtime=20
;thread
loops=10
"

### Test case parameter configuration.
## 1 - support MSI-x interrupt 82599  function.
#
QUERY_KEYWORDS_82599="Intel Corporation 82599"

## 2 - PCIe 3.0 backward compatibility.
# Query the raid008 keyword.
RAID3008_QUERY_KEYWORDS="SAS3008"
#
RAID3008_SPEED_VALUE="8GT/s"
#
RAID3008_WIDTH_VALUE="x8"
# FIO tools runing time.
RAID3008_FIO_TIME=60
# Query the ES3000 keyword.
ES3000_QUERY_KEYWORDS="Device 0123"
#
ES3000_SPEED_VALUE="8GT/s"
#
ES3000_WIDTH_VALUE="x4"
#
ES3000_FIO_TIME=180
#
BACK_IP="192.168.50.153"
# set the developer
DEVELOPER=""
# test module name
Module="pcie"
